name: EcoFramework
main: jp.minecraftuser.ecoframework.plugin.EcoFramework
version: ${project.version}
commands:
  ecoframework:
    description: EcoFramework maintenance command.
    usage: /<command> xxx
    