name: EcoFramework
main: jp.minecraftuser.ecoframework.plugin.EcoFramework
version: ${project.version}
api-version: 1.18
commands:
  ecoframework:
    description: EcoFramework maintenance command.
    usage: /<command> xxx
    permission: ecoframework
  ecoframework permissions:
    description: Show All EcoFramework plugin permissions.
    usage: /<command> xxx
    permission: ecoframework.permissions
  ecoframework accept:
    description: Accept confirm command.
    usage: /<command>
    permission: ecoframework.accept
  ecoframework cancel:
    description: Cancel confirm command.
    usage: /<command>
    permission: ecoframework.cancel
